version: '3'

services:
  postgres:
    image: postgres:13.5
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=funny-bot
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
